name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Build Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python@v3
              with:
                  python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
                  architecture: 'x64'
            - uses: actions/checkout@v3
            - uses: logikal-code/pip-install@v1.0.0
            - uses: browser-actions/setup-geckodriver@latest
            - uses: c-hive/gha-yarn-cache@v2
            - name: Install dependencies
              run: yarn install
            - name: Build
              run: yarn build
            - name: Test
              run: pytest --webdriver Firefox --cov=dash_extensions --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov-report=xml tests
            - name: Upload Results
              uses: actions/upload-artifact@v3.1.0
              with:
                  path: junit/test-results-${{ matrix.python-version }}.xml
              if: ${{ always() }}

            - name: Upload to Codecov
              uses: codecov/codecov-action@v3.1.0
