name: CI
on: [push]
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.10'
    steps:
      - uses: actions/checkout@v3  
      - uses: logikal-code/pip-install@v1.0.0
      - run: which dash-generate-components
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build # will run `yarn build` command
