name: CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        name: Build Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-python
              with:
                  python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
                  architecture: 'x64'
            - uses: actions/checkout
            - uses: logikal-code/pip-install
            - uses: browser-actions/setup-geckodriver
            - uses: c-hive/gha-yarn-cache
            - name: Install dependencies
              run: yarn install
            - name: Build & Test
              run: |
                  yarn build   
                  pytest --webdriver Firefox --cov=dash_grocery --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov-report=xml tests
            - name: Upload Results
              uses: actions/upload-artifact
              with:
                  path: junit/test-results-${{ matrix.python-version }}.xml
              if: ${{ always() }}

            - name: Upload to Codecov
              uses: codecov/codecov-action
