name: CI
on: [push]
jobs:
  build:
    name: Build Test
    runs-on: ubuntu-latest
    env:
      PYTHON: '3.10'
    steps:
      - uses: actions/checkout@latest     
      - uses: logikal-code/pip-install@latest    
      - uses: borales/actions-yarn@latest
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@latest
        with:
          cmd: build # will run `yarn build` command
